### ISSUE TITLE
Link broken for the keyword Source in readme

### ISSUE THREAD

**Issue by samrudh** [gramener/gramex-nlg#1]
Link for the keyword **Source** is broken at Line 30 in README.md
Link: https://github.com/gramener/gramex/blob/master/gramex/apps/guide/nlg/gramex.yaml

**Comment by jaidevd** [comment]
Thanks for pointing this out, @samrudh 
It seems a few more things are broken in the docs as well. I'll get to this week, but would you like to get involved in fixing this as well?

**Comment by samrudh** [comment]
Yes, I would be definitely interested. Currently, I am trying to set up the tool on my machine. I will go through one run following the docs.

**Comment by jaidevd** [comment]
Great, let me know when you're ready.
