### ISSUE TITLE
Installation fails at step # 2

### ISSUE THREAD

**Issue by mankoven** [gramener/gramex-nlg#11]
Gramex setup command fails with the below error. Could you please assist. 
pip install nlg was successful

![image](https://user-images.githubusercontent.com/46864655/71874868-02f1dc00-3149-11ea-97c8-867a97469917.png)

**Comment by jaidevd** [comment]
Please try again, @mankoven 
Follow the instructions in the README. Only, when doing the pip install, you might have to do 

```bash
pip install --upgrade nlg
```

since an older version of NLG may be already present.

**Comment by jaidevd** [comment]
Fixed in #12
