### ISSUE TITLE
ValueError while importing spacy.matcher

### ISSUE THREAD

**Issue by samrudh** [gramener/gramex-nlg#2]
ValueError: spacy.strings.StringStore size changed, may indicate binary incompatibility. Expected 112 from C header, got 88 from PyObject

Above error is thrown while importing spacy Matcher
`    from spacy.matcher import PhraseMatcher
`

Spacy version: spacy=2.2 
Platform: Macbook

Resolution: 
Downgrade to spacy 2.1
`pip install spacy==2.1`

**Comment by jaidevd** [comment]
Closed in  #10
