### ISSUE TITLE
Reorder Templates in each Narrative

### ISSUE THREAD

**Issue by mankoven** [gramener/gramex-nlg#27]
We need to have a way to reorder templates in a Narrative. One approach is to provide UP / DOWN arrow next to each template. This will allow reordering templates.

**Comment by jaidevd** [comment]
@mankoven please run the app from the dev branch once - this should be working now with dragging and dropping previews in the web app.

**Comment by mankoven** [comment]
@jaidevd Validated the fix in dev branch, reorder sequence (with drag & drop) works. Closing the issue.
