### ISSUE TITLE
Default styling for template display

### ISSUE THREAD

**Issue by mankoven** [gramener/gramex-nlg#28]
The template text displayed should come with a default style. We should have an ability to bold, italics, underline, bullet list the text in Narrative.

**Comment by jaidevd** [comment]
@mankoven Please check once - styling options should be available now.

**Comment by mankoven** [comment]
@jaidevd Validated font style for Bold, Italics, Underline, Paragraph & Bullet list. 
When the narrative is saved and used by a different user, the rendering fails.

**Comment by jaidevd** [comment]
Fixed in #36
