### ISSUE TITLE
Templatize output post-processing

### ISSUE THREAD

**Issue by samrudh** [gramener/gramex-nlg#3]
Summary
Templatize output provides a dictionary of tokens with the corresponding list of templates. We expect a full template as the output compatible with tornado

Steps to reproduce
run a templatize function with valid text, fh_args, and data frame

What is the current bug behavior?
Currently, intermediate output is provided which needs post-processing

What is the expected correct behavior?
A tornado template as an output 

Possible fixes
A post-processing functionality encapsulated inside the templatize function.
/label ~bug

**Comment by jaidevd** [comment]
Thanks @samrudh 
There's a bunch of functionality that still lies in the frontend app, and hasn't been ported over to the Python package. This is happening because of that. I'll check it out.

**Comment by jaidevd** [comment]
@samrudh Please  check this once more. The README has an example of how `templatize` works.

**Comment by samrudh** [comment]
Yup, now it's working and output is clean. Thanks
