### ISSUE TITLE
Embed code should have reference to data

### ISSUE THREAD

**Issue by mankoven** [gramener/gramex-nlg#34]
The Embed code snipped should have conditional logic

- Check for Formhandler URL to retrieve data
- If Formhandler URL is NOT present, show static text from Narrative (fall back to the original text used while creating narrative)

![image](https://user-images.githubusercontent.com/46864655/73742732-122d6f00-4773-11ea-80fa-cf9a296603b1.png)

**Comment by jaidevd** [comment]
Fixed in #36
