### ISSUE TITLE
Installation has failed: No module named builtins 

### ISSUE THREAD

**Issue by james2a** [gramener/gramex-nlg#47]
Hello,
I'm getting the following error message during the installation.

pip install nlg -e .
Obtaining file:///home/xxxx/gramex-nlg
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/xxxx/gramex-nlg/setup.py", line 9, in <module>
        import builtins
    ImportError: No module named builtins
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/xxxx/gramex-nlg/

Thanks in advance for helping.

Regards

James

**Comment by jaidevd** [comment]
Hi @james2a  - how did you fix this?

**Comment by james2a** [comment]
Hello Jaidev,
I used plp3 instead of plp.

Regards

James
