### ISSUE TITLE
Module import error

### ISSUE THREAD

**Issue by VivekKakadeIncedo** [gramener/gramex-nlg#55]
I am getting an error on this statement - from nlg.search import templatize
Error is: OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
<img width="410" alt="error" src="https://user-images.githubusercontent.com/60430556/99962355-11270600-2db6-11eb-98ab-c5e2a1488893.PNG">

**Comment by jaidevd** [comment]
Hi @VivekKakadeIncedo 

Please try the following:
```bash
python -m spacy download en_core_web_sm
```
restart the jupyter kernel, and try again.

Thanks,

**Comment by VivekKakadeIncedo** [comment]
Thanks Jaidev for quick response. It worked!

Regards,
Vivek
