### ISSUE TITLE
Error while using pickel with nuggets

### ISSUE THREAD

**Issue by palaklanger** [gramener/gramex-nlg#59]
I created a few nuggets , defined a dictionary for it and trying to dump it using pickle but it is giving error. 

nugget_map={}
nugget_map['nugget1']=nugget1
nugget_map['nugget2']=nugget2
with open('nugget_map.pickle', 'wb') as handle:
        pickle.dump(nugget_map, handle, protocol=pickle.HIGHEST_PROTOCOL)

PicklingError                             Traceback (most recent call last)
<ipython-input-66-a1a19ab0d96b> in <module>
      1 data_train=pd.read_csv('data_new.csv')
----> 2 nugget_map=train_data(data_train)

<ipython-input-65-8065a65cdbc2> in train_data(train)
     85     #nugget_map = pd.DataFrame.from_dict(nugget_map)
     86     with open('nugget_map.pickle', 'wb') as handle:
---> 87         pickle.dump(nugget_map, handle, protocol=pickle.HIGHEST_PROTOCOL)
     88     return nugget_map

**_PicklingError: Can't pickle <function <lambda> at 0x7f30354f98c8>: attribute lookup <lambda> on nlg.narrative failed_**

Can you please check this, or can you please share some workaround how can I dump the nugget map.

**Comment by jaidevd** [comment]
Hi @palaklanger 
Nuggets cannot be saved / loaded through pickle. To serialize and deserialize them, please use:

```python
>>> x = json.dumps(nugget.to_dict())   # JSON string for the nugger
>>> Nugget.from_json(x)
```
