### ISSUE TITLE
Functionality to manually update tornado template

### ISSUE THREAD

**Issue by samrudh** [gramener/gramex-nlg#7]
In the case when existing templatize missed some part of the text to identify as a "keyword", we would like to have a functionality to add it in the end.

**Comment by jaidevd** [comment]
Closed in #17 

@samrudh please check the [intro notebook](https://github.com/gramener/gramex-nlg/blob/dev/examples/intro-narrative-api.ipynb) for examples of how to manually add / change variables and edit their templates.

Thanks,
